require("config/variables")
require("config/workspaces")
require("config/env")
require("config/autostart")
require("config/monitors")
require("config/settings")
require("config/keybinds")
require("config/language")
