source = ~/Config/home-manager/programs/hypr/configs/environments.conf
source = ~/Config/home-manager/programs/hypr/configs/monitors.conf
source = ~/Config/home-manager/programs/hypr/configs/utils.conf
source = ~/Config/home-manager/programs/hypr/configs/languages.conf
source = ~/Config/home-manager/programs/hypr/configs/animations.conf
source = ~/Config/home-manager/programs/hypr/configs/workspaces.conf
source = ~/Config/home-manager/programs/hypr/configs/decorations.conf
source = ~/Config/home-manager/programs/hypr/configs/autostart.conf
source = ~/Config/home-manager/programs/hypr/configs/binds/binds.conf
