bind = $mainMod, E, exec, $fileManager
bind = $mainMod, T, exec, $terminal
bind = $mainMod, R, fullscreen
bind = $mainMod, Q, exec, pkill $menu || $menu --show drun
bind = $mainMod, B, exec, $browser
#bind = $mainMod, F, exec, hyprctl keyword general:gaps_out 10 & hyprctl keyword general:border_size 2 & hyprctl keyword decoration:rounding 10 & hyprctl keyword general:gaps_in 5
#bind = $mainMod  SHIFT, F, exec, hyprctl keyword general:gaps_out 0 & hyprctl keyword general:border_size 0 & hyprctl keyword decoration:rounding 0 & hyprctl keyword general:gaps_in 0
bind = $mainMod, C, killactive,
bind = $mainMod, L, exit,
bind = $mainMod, V, togglefloating,

bind = $mainMod, S, exec, grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png | wl-copy

bind = $mainMod, Shift+Alt, exec, hyprctl switchxkblayout [device] next
