general { 
    gaps_in = 5
    gaps_out = 10

    border_size = 2

    col.active_border = rgba(595959aa)
    col.inactive_border = rgba(1914141a)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}

#decoration {
#    rounding = 10
#
#    active_opacity = 1.0
#    inactive_opacity = 1.0
#
#    drop_shadow = false
#    shadow_range = 4
#    shadow_render_power = 3
#    col.shadow = rgba(1a1a1aee)
#
#    blur {
#        enabled = false
#        size = 3
#        passes = 1
#        
#        vibrancy = 0.1696
#    }
#}

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 1.0

    # In newer Hyprland, shadows are nested like this:
    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = false
        size = 3
        passes = 1
        vibrancy = 0.1696
    }
}
