$mainMod = SUPER
$terminal = alacritty
$fileManager = thunar
$menu = wofi
$codeeditor = zed
$browser = firefox

$firstMonitor = DP-3
$secondMonitor = HDMI-A-1

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct
