# First monitor (DP-3)
workspace=1, monitor:$firstMonitor, persistent:true
workspace=2, monitor:$firstMonitor, persistent:true
workspace=3, monitor:$firstMonitor, persistent:true
workspace=4, monitor:$firstMonitor, persistent:true

# Second monitor (HDMI-A-1)
workspace=5, monitor:$secondMonitor, persistent:true
workspace=6, monitor:$secondMonitor, persistent:true
workspace=7, monitor:$secondMonitor, persistent:true
